stages:
  limpieza:
    cmd: python src/data/limpieza.py
    deps:
    - data/raw/bird_migration_with_origin_destination.csv
    - src/data/limpieza.py
    outs:
    - data/interim/bird_migration_OD_clean.csv
  procesado:
    cmd: python src/features/procesado.py
    deps:
    - data/interim/bird_migration_OD_clean.csv
    - src/features/procesado.py
    outs:
    - data/processed/bird_migration_OD_scaled.csv
